package br.com.eletricguardian.app.byd

/**
 * Nomes de propriedade do ICarPropertyService da BYD para varredura pelo provider
 * (com.byd.car.server). A lista base veio da tabela do Overdrive (os nomes que
 * ele lê como app comum); o provider é consultado por nome, não pelo ID hex.
 *
 * Alguns campos que não aparecem na tabela do Overdrive (velocidade, marcha,
 * bateria 12V, temperatura externa) entram como CANDIDATOS, seguindo a convenção
 * de nomes da BYD. A primeira build é de descoberta: varre tudo com o carro
 * parado e registra no log o que respondeu, para calibrarmos em cima do real.
 */
object BydProperties {

    /** Nomes conhecidos (tabela do Overdrive) — leituras confiáveis. */
    val KNOWN = listOf(
        "AC_CTRL_MODE_SET",
        "AC_CTRL_SOURCE_SET",
        "Ac.AC_CYCLE_MODE_SET",
        "Ac.AC_DEFROST_FRONT_STATE",
        "Ac.AC_DEFROST_FRONT_STATE_SET",
        "Ac.AC_DEFROST_REAR_STATE",
        "Ac.AC_DEFROST_REAR_STATE_SET",
        "Ac.AC_TEMP_INSIDE",
        "Ac.AC_WIND_LEVEL_SET",
        "Adas.ADAS_DOW_STATE_SET",
        "Adas.ADAS_DOW_SWITCH_STATE",
        "Adas.ADAS_DOW_WARN_LEFT",
        "Adas.ADAS_DOW_WARN_RIGHT",
        "Adas.ADAS_ECTB_STATE_SET",
        "Adas.ADAS_ELKA_SWITCH_SET",
        "Adas.ADAS_ELKA_SWITCH_STATE",
        "Adas.ADAS_ESP_STATE",
        "Adas.ADAS_ESP_STATE_SET",
        "Adas.ADAS_FCTA_SWITCH_SET",
        "Adas.ADAS_FCTA_SWITCH_STATUS",
        "Adas.ADAS_FCTB_SWITCH_SET",
        "Adas.ADAS_FCTB_SWITCH_STATUS",
        "Adas.ADAS_FCW_LEVEL_SET",
        "Adas.ADAS_FCW_LEVEL_STATUS",
        "Adas.ADAS_FL_BLIND_SPOT_ALARM_ACTIVE_SIGNAL_STATUS",
        "Adas.ADAS_FR_BLIND_SPOT_ALARM_ACTIVE_SIGNAL_STATUS",
        "Adas.ADAS_HAS_BSD",
        "Adas.ADAS_ISLA_SWITCH_SET",
        "Adas.ADAS_ISLA_SWITCH_STATUS_5R13V",
        "Adas.ADAS_ISLC_SWITCH_SET",
        "Adas.ADAS_ISLC_SWITCH_STATUS_5R13V",
        "Adas.ADAS_RCTA_STATE_SET",
        "Adas.ADAS_RCW_STATE_SET",
        "Adas.ADAS_RCW_SWITCH_STATE",
        "Adas.ADAS_RIGHT_RADAR_LCA_WARNINGLEFT",
        "Adas.ADAS_RIGHT_RADAR_LCA_WARNINGRIGHT",
        "Adas.ADAS_RIGHT_RADAR_RCTA_WARNINGLEFT",
        "Adas.ADAS_RIGHT_RADAR_RCTA_WARNINGRIGHT",
        "Adas.ADAS_RTCA_SWITCH_STATE",
        "Adas.ADAS_RTCB_SWITCH_STATE",
        "Adas.ADAS_SLR_STATUS_SET",
        "Adas.ADAS_SLW_FUNC_SWITCH_STATE",
        "Adas.ADAS_SLW_FUNC_SWITCH_STATE_SET",
        "Adas.ADAS_TLA_SWITCH_SET",
        "Adas.ADAS_TLA_SWITCH_STATUS_5R13V",
        "Adas.OMS_DRIVER_DETECTION_RESULT",
        "Adas.OMS_PASSENGER_DETECTION_RESULT",
        "BODYWORK_EMERGENCY_ALARM_STATE",
        "Body.ATMOSPHERE_LIGHT_MUSIC_EXECUTE",
        "Body.ATMOSPHERE_LIGHT_SWITCH_EXECUTE",
        "Body.BACK_DOOR_MAINTENANCE_STATUS",
        "Body.BACK_DOOR_OPENING_STATUS_FEEDBACK",
        "Body.BACK_DOOR_OPEN_CLOSE_STATUS",
        "Body.BACK_DOOR_OPEN_STATUS_CONFIRM",
        "Body.BACK_DOOR_POSITION_FEEDBACK",
        "Body.BACK_DOOR_TRIGGER_ATOM",
        "Body.BODYWORK_SUNSHADE_PANEL_PERCENT",
        "Body.BODYWORK_SUNSHADE_PANEL_PERCENT_SET",
        "Body.INSIDE_LIGHT_STATE_SET",
        "Body.LF_DOOR_STATUS_FLAG",
        "Body.LR_DOOR_STATUS_FLAG",
        "Body.RF_DOOR_STATUS_FLAG",
        "Body.RR_DOOR_STATUS_FLAG",
        "Body.SMART_ENTRY_BLUETOOTH_STATUS",
        "Bodywork.BODYWORK_FUEL_TANK_CAP",
        "Bodywork.BODYWORK_HOOD",
        "Bodywork.BODYWORK_LEFT_HAND_FRONT_DOOR",
        "Bodywork.BODYWORK_LEFT_HAND_REAR_DOOR",
        "Bodywork.BODYWORK_LUGGAGE_DOOR",
        "Bodywork.BODYWORK_RIGHT_HAND_FRONT_DOOR",
        "Bodywork.BODYWORK_RIGHT_HAND_REAR_DOOR",
        "Charging.CHARGING_BATTERRY_DEVICE_STATE",
        "Charging.CHARGING_CHARGER_WORK_STATE",
        "Charging.CHARGING_CHARGE_CAPACITY",
        "Charging.WIRELESS_CHARGING_LEFT_STATE",
        "Charging.WIRELESS_CHARGING_LEFT_SWITCH_DIRECT",
        "Charging.WIRELESS_CHARGING_LEFT_SWITCH_SET",
        "Charging.WIRELESS_CHARGING_RIGHT_STATE",
        "Charging.WIRELESS_CHARGING_RIGHT_SWITCH_DIRECT",
        "Charging.WIRELESS_CHARGING_RIGHT_SWITCH_SET",
        "Charging.WIRELESS_CHARGING_STATE",
        "Charging.WIRELESS_CHARGING_SWITCH_SET",
        "DoorLock.COMMAND_AREA_CHILDLOCK_LEFT_SET",
        "DoorLock.COMMAND_AREA_CHILDLOCK_RIGHT_SET",
        "ENERGY_MODE_INSTRUMENT",
        "ENERGY_MODE_SET",
        "ENGINE_FRONT_MOTOR_SPEED",
        "ENGINE_FRONT_MOTOR_TORQUE",
        "ENGINE_POWER",
        "ENGINE_REAR_MOTOR_SPEED",
        "Energy.ENERGY_ROAD_SURFACE_MODE",
        "Engine.DRIFT_MODE_SWITCH_CONFIG",
        "Engine.DRIFT_MODE_SWITCH_STATUS",
        "Engine.ENGINE_SPEED",
        "Engine.ENGINE_SPEED_GB",
        "Instrument.CHARGING_CHARGE_PERCENT_DD",
        "Instrument.CHARGING_CHARGE_POWER_DD",
        "Instrument.CHARGING_CHARGE_REST_HOUR_DD",
        "Instrument.CHARGING_CHARGE_REST_MINUTE_DD",
        "Instrument.INSTRUMENT_2IN1_CURRENT_JOURNEY_DRIVE_MILEAGE",
        "Instrument.INSTRUMENT_2IN1_CURRENT_JOURNEY_DRIVE_TIME",
        "Instrument.INSTRUMENT_DD_DEPUTY_SAFETYBELT_STATE",
        "Instrument.INSTRUMENT_DD_MAIN_SAFETYBELT_STATE",
        "Instrument.INSTRUMENT_HEADLIGHT_CONTROL_FEEDBACK",
        "Instrument.INSTRUMENT_HEADLIGHT_CONTROL_SET",
        "Instrument.LB_TYRE_TEMPERATURE",
        "Instrument.LF_TYRE_TEMPERATURE",
        "Instrument.MUSIC_PLAYBACK_PROGRESS_SET",
        "Instrument.MUSIC_SOURCE_SET",
        "Instrument.MUSIC_STATE_SET",
        "Instrument.NAVIGATION_ACTIVATED_SET",
        "Instrument.NAVI_ESTIMATED_MILEAGE_SET",
        "Instrument.NAVI_ESTIMATED_TIME_SET",
        "Instrument.NAVI_TYPE_SET",
        "Instrument.RB_TYRE_TEMPERATURE",
        "Instrument.RF_TYRE_TEMPERATURE",
        "Light.AMBIENT_FRONT_BRIGHTNESS",
        "Light.AMBIENT_FRONT_BRIGHTNESS_ALT",
        "Light.AMBIENT_FRONT_COLOR",
        "Light.AMBIENT_REAR_BRIGHTNESS",
        "Light.AMBIENT_REAR_BRIGHTNESS_ALT",
        "Light.AMBIENT_REAR_COLOR",
        "Light.ATMOSPHERE_ADJUST_AREA_SET",
        "Light.ATMOSPHERE_CUSTOM_BRIGHTNESS",
        "Light.ATMOSPHERE_CUSTOM_BRIGHTNESS_SET",
        "Light.ATMOSPHERE_CUSTOM_COLOR",
        "Light.ATMOSPHERE_CUSTOM_COLOR_SET",
        "Light.ATMOSPHERE_MAIN_SWITCH_SET",
        "Light.ATMOSPHERE_MAIN_SWITCH_STATUS",
        "Light.ATMOSPHERE_VEHICLE_BRIGHTNESS_SET",
        "Light.LIGHT_CMD_DOUBLE_FLASH_STATE",
        "Light.LIGHT_CMD_SEQUENTIAL_STATE",
        "Light.LIGHT_DAY_RUNNING_LIGHT_AUTO_STATE",
        "Light.LIGHT_EMERGENCY_WARNING_LIGHT_STATE",
        "Light.LIGHT_HIGH_BEAM_LIGHT",
        "Light.LIGHT_LOW_BEAM_LIGHT",
        "Light.LIGHT_PIXEL_HEADLIGHT_ALS_STATE",
        "Light.LIGHT_REAR_FOG_LAMPS",
        "Light.LIGHT_TURN_SIGNAL_LIGHT",
        "Mirror.BODYWORK_REARVIEW_MIRROR_SET",
        "Mirror.HAVE_REARVIEW_MIRROR_AUTO_FOLD",
        "Pm25.ANION_STATE",
        "Pm25.ANION_STATE_SET",
        "Rear.REAR_VIEW_MIRROR_STATE",
        "STATISTIC_AVERAGE_BATTERY_TEMP",
        "STATISTIC_HIGHEST_BATTERY_TEMP",
        "STATISTIC_HIGHEST_BATTERY_VOLTAGE",
        "STATISTIC_LOWEST_BATTERY_TEMP",
        "STATISTIC_LOWEST_BATTERY_VOLTAGE",
        "SafetyBelt.REMINDER_MASK",
        "Sensor.SENSOR_AUTO_SLOPE",
        "Setting.LEFT_REAR_DOOR_CHILD_LOCK_STATUS",
        "Setting.RIGHT_REAR_DOOR_CHILD_LOCK_STATUS",
        "Setting.SETTING_AC_CHARGING_CURRENT_LIMIT_CONFIG_STATUS",
        "Setting.SETTING_AC_CHARGING_CURRENT_LIMIT_STATUS",
        "Setting.SETTING_AC_CHARGING_CURRENT_LIMIT_STATUS_SET",
        "Setting.SETTING_CPD_SWITCH_STATUS",
        "Setting.SETTING_CPD_SWITCH_STATUS_SET",
        "Setting.SETTING_DRAG_MODE_CURRENT_STATE",
        "Setting.SETTING_FRONT_RAIN_WIPER_SPEED",
        "Setting.SETTING_TARGET_DRIVING_MODE",
        "Setting.SETTING_TARGET_DRIVING_MODE_ALT",
        "Setting.SET_BRIGHTNESS_GEAR_SET",
        "Setting.SET_CAR_DOOR_LOCK_SET",
        "Setting.SET_DRIVER_SEAT_HEATING_STATE",
        "Setting.SET_DRIVER_SEAT_VENTILATING_STATE",
        "Setting.SET_HUD_CONFIG",
        "Setting.SET_HUD_SWITCH_SET",
        "Setting.SET_HUD_SWITCH_STATUS_FEEDBACK",
        "Setting.SET_IAL_COLOR_CONFIG",
        "Setting.SET_ITAC_CONFIG",
        "Setting.SET_ITAC_INTELLIGENT_TORQUE_CONTROL_FLAG",
        "Setting.SET_ITAC_STATE",
        "Setting.SET_ITAC_STATE_SET",
        "Setting.SET_LANE_LINE_CURVATURE",
        "Setting.SET_LF_MEMORY_LOCATION_SET",
        "Setting.SET_LF_MEMORY_LOCATION_WAKE_SET",
        "Setting.SET_OUTSIDE_REARVIEW_MIRROR_FOLD_SET",
        "Setting.SET_PAD_ROTATION_SET",
        "Setting.SET_PASSENGER_SEAT_HEATING_STATE",
        "Setting.SET_PASSENGER_SEAT_VENTILATING_STATE",
        "Setting.SET_REMOTE_CONTROL_UNLOCKING_SET",
        "Setting.SET_RF_MEMORY_LOCATION_SET",
        "Setting.SET_RF_MEMORY_LOCATION_WAKE_SET",
        "Setting.SET_VOICE_CTRL_BACK_DOOR_SET",
        "Statistic.STATISTICS_MILEAGE_AFTER_ZEROING",
        "Statistic.STATISTIC_BATTERY_HEALTHY_INDEX",
        "Statistic.STATISTIC_ELEC_DRIVING_RANGE",
        "Statistic.STATISTIC_ELEC_PERCENTAGE",
        "Statistic.STATISTIC_EV_DRIVING_MILEAGE",
        "Statistic.STATISTIC_FUEL_DRIVING_RANGE",
        "Statistic.STATISTIC_FUEL_PERCENTAGE",
        "Statistic.STATISTIC_MILEAGE_EV",
        "Statistic.STATISTIC_MILEAGE_HEV",
        "Statistic.STATISTIC_THIS_TRIP_TOTAL_ELEC_CONSUMPTION",
        "Statistic.STATISTIC_TOTAL_MILEAGE",
        "Tailgate.BACKDOOR_POSITION_FEEDBACK",
        "Tailgate.BACK_DOOR_STATUS_FLAG",
        "Tailgate.DOWN_BACK_DOOR_CURRENT_POSITION",
        "Wiper.FRONT_WIPER_LEVEL",
        "Wiper.REAR_AREA_STATE",
    )

    /**
     * Candidatos para os campos que faltam. São palpites pela convenção
     * Categoria.CATEGORIA_CAMPO; confirmados na varredura de descoberta no carro.
     */
    val CANDIDATES = listOf(
        // Velocidade do veículo (km/h)
        "Speed.SPEED_CURRENT_SPEED", "Speed.CURRENT_SPEED", "Speed.VEHICLE_SPEED",
        "Speed.SPEED_VEHICLE_SPEED", "Instrument.VEHICLE_SPEED",
        "Instrument.INSTRUMENT_VEHICLE_SPEED", "Instrument.INSTRUMENT_SPEED",
        // Marcha (P/R/N/D)
        "Gearbox.GEARBOX_GEAR_POSITION", "Gearbox.GEAR_POSITION",
        "Gearbox.GEARBOX_SHIFT_POSITION", "Instrument.GEAR_POSITION",
        "Instrument.INSTRUMENT_GEAR_POSITION", "Instrument.INSTRUMENT_GEAR",
        // Bateria auxiliar 12V (tensão)
        "Statistic.STATISTIC_LOW_VOLTAGE_BATTERY", "Statistic.STATISTIC_12V_BATTERY_VOLTAGE",
        "Body.BODYWORK_BATTERY_VOLTAGE", "Instrument.INSTRUMENT_LOW_BATTERY_VOLTAGE",
        "Instrument.LOW_VOLTAGE_BATTERY_VOLTAGE",
        // Temperatura externa (°C)
        "Ac.AC_TEMP_OUTSIDE", "Ac.AC_TEMP_OUT_CAR", "Ac.AC_OUTSIDE_TEMP",
        "Instrument.OUTSIDE_TEMPERATURE", "Instrument.INSTRUMENT_OUTSIDE_TEMP",
        "Sensor.SENSOR_OUTSIDE_TEMPERATURE", "Sensor.OUTSIDE_TEMPERATURE",
        // Nível de energia/ignição e torque, para completar o painel
        "Body.AUTO_SYSTEM_STATE", "Instrument.INSTRUMENT_POWER_STATE",
    )

    /** Tudo que a varredura de descoberta tenta. */
    val ALL = KNOWN + CANDIDATES
}
