#!/usr/bin/env bash
# Electric Guardian on a VPS where nginx already serves other sites (ports 80/443 taken).
# Docker runs only the service on 127.0.0.1:8787; nginx + certbot front it. Other sites are not touched.
#   sudo APP_HOST=guardian.allysongrolli.com.br VIEW_HOST=cam.guardian.allysongrolli.com.br \
#        ACME_EMAIL=voce@email.com ADMIN_EMAIL=voce@email.com bash deploy/install-nginx.sh
set -euo pipefail
cd "$(dirname "$0")"
: "${APP_HOST:?defina APP_HOST}" "${VIEW_HOST:?defina VIEW_HOST}" "${ACME_EMAIL:?defina ACME_EMAIL}"
export DEBIAN_FRONTEND=noninteractive

command -v docker >/dev/null || curl -fsSL https://get.docker.com | sh
command -v certbot >/dev/null || { apt-get update -qq && apt-get install -y -qq certbot python3-certbot-nginx; }

if [ ! -f .env ]; then
  cat > .env <<EOF
APP_HOST=$APP_HOST
VIEW_HOST=$VIEW_HOST
ACME_EMAIL=$ACME_EMAIL
ALLOW_SIGNUP=${ALLOW_SIGNUP:-1}
CONTROL_ENABLED=${CONTROL_ENABLED:-1}
SESSION_SECRET=$(head -c 48 /dev/urandom | base64 | tr -d '\n=/+')
EOF
  chmod 600 .env
fi

COMPOSE="docker compose -f docker-compose.nginx.yml"
$COMPOSE up -d --build

SITE=/etc/nginx/sites-available/electric-guardian
cat > "$SITE" <<EOF
# Electric Guardian — generated by install-nginx.sh
map \$http_upgrade \$eg_conn { default upgrade; '' close; }
server {
    listen 80;
    listen [::]:80;
    server_name $APP_HOST $VIEW_HOST;
    client_max_body_size 8m;
    location / {
        proxy_pass http://127.0.0.1:8787;
        proxy_http_version 1.1;
        proxy_set_header Host \$host;
        proxy_set_header X-Forwarded-For \$remote_addr;
        proxy_set_header X-Forwarded-Proto \$scheme;
        proxy_set_header Upgrade \$http_upgrade;
        proxy_set_header Connection \$eg_conn;
        proxy_buffering off;
        proxy_request_buffering off;
        proxy_read_timeout 1d;
        proxy_send_timeout 1d;
    }
}
EOF
ln -sf "$SITE" /etc/nginx/sites-enabled/electric-guardian
nginx -t
systemctl reload nginx
certbot --nginx --non-interactive --expand --agree-tos -m "$ACME_EMAIL" --redirect -d "$APP_HOST" -d "$VIEW_HOST"
nginx -t && systemctl reload nginx

for i in $(seq 1 40); do curl -fs http://127.0.0.1:8787/healthz >/dev/null && break; sleep 2; done
if [ -n "${ADMIN_EMAIL:-}" ]; then
  ADMIN_PASS="${ADMIN_PASSWORD:-$(head -c 18 /dev/urandom | base64 | tr -d '\n=/+')}"
  $COMPOSE exec -T eg node scripts/admin.mjs create-user "$ADMIN_EMAIL" "$ADMIN_PASS" "Admin" && \
    echo ">> usuário: $ADMIN_EMAIL  senha: $ADMIN_PASS   (troque no painel)"
fi
echo ">> pronto: https://$APP_HOST"
